This is makeindex, version 2.16 [MiKTeX 25.4].
Scanning style file ./MU_Thesis_Style.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file MU_Thesis_Style.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file MU_Thesis_Style.acr....done (8 lines written, 0 warnings).
Output written in MU_Thesis_Style.acr.
Transcript written in MU_Thesis_Style.alg.
